export const BrawlersData = () => [
  {
    id: 1,
    nome: "Shelly",
    classe: "Destruidores",
    raridade: "Inicial",
    descricao: "Shelly é a lutadora perfeita: confiável, durona e imbatível com a espingarda. Com tantas qualidades assim, ela nunca entendeu como o Colt virou o queridinho da galera...",
    imagem: "https://www.brawlstarsdicas.com.br/wp-content/uploads/2017/06/shelly-wiki-brawl-stars-dicas-OC4cV8-150x150.png.webp",  
  },
  {
    id: 2,
    nome: "Colt",
    classe: "Destruidores",
    raridade: "Raro",
    descricao: "CTodo mundo que visita o Starr Park quer ver o Colt de perto, pois o cara é boa-pinta, carismático e cheio de truques com suas pistolas duplas. Não é o herói que você pediu, mas é o herói que você tem. Sempre no lugar errado na hora certa. Ele é repleto de confiança e adora se olhar no espelho!",
    imagem: "https://www.brawlstarsdicas.com.br/wp-content/uploads/2017/06/colt-wiki-brawl-stars-dicas-DvpoGs-150x150.png.webp",
  },
  {
    id: 3,
    nome: "Bull",
    classe: "Tanque",
    raridade: "Raro",
    descricao: "Bull não é mais tão despreocupado quanto na juventude, mas só porque seus dias de bagunça ficaram para trás não significa que ele não vai esmagar alguém que estiver pedindo por isso.",
    imagem: "https://www.brawlstarsdicas.com.br/wp-content/uploads/2019/04/bull-wiki-brawl-stars-dicas-150x150.png",
  },
  {
    id: 4,
    nome: "Piper",
    classe: "Tiro Precisos",
    raridade: "epico",
    descricao: "Piper não quer nada mais do que ser a padeira da vila, distribuindo tortas, biscoitos e outros doces deliciosos! Só não pergunte sobre o seu passado se não quiser acabar no forno.",
    imagem: "https://www.brawlstarsdicas.com.br/wp-content/uploads/2017/06/piper-wiki-brawl-stars-dicas-150x150.png",
  },
  {
    id: 5,
    nome: "Kit",
    classe: "Suporte",
    raridade: "Lendário",
    descricao: "Preso dando autógrafos para seus fãs enlouquecidos no Starr Toon Studios, o superstar cartunesco Kit frequentemente sonha em voltar a ser relevante na indústria, respeitado por seu talento de ator em vez da sua aparência.",
    imagem: "https://www.brawlstarsdicas.com.br/wp-content/uploads/2017/06/kit-wiki-brawl-stars-dicas-150x150.png.webp",
  },
  {
    id: 6,
    nome: "Maisie",
    classe: "Tiro-Precisos",
    raridade: "epico",
    descricao: "Maisie trabalha como chefe de segurança, mas no fundo adora situações perigosas. Às vezes, parece até que ela tem uma mãozinha na criação delas.",
    imagem: "https://www.brawlstarsdicas.com.br/wp-content/uploads/2017/06/maisie-wiki-brawl-stars-dicas-150x150.png.webp",
  },
  {
    id: 7,
    nome: "Poco",
    classe: "Suporte",
    raridade: "Raro",
    descricao: "MPoco acredita que a música pode mudar a vida das pessoas. Ele é tão entusiástico que nunca para de tocar, mesmo quando pedem para ele parar!",
    imagem: "https://www.brawlstarsdicas.com.br/wp-content/uploads/2021/02/poco-wiki-brawl-stars-dicas-150x150.png",
  },
  {
    id: 8,
    nome: "Meg",
    classe: "Tanque",
    raridade: "Lendário",
    descricao: "Satisfeita em trabalhar nos bastidores com seu fiel traje mecha, Meg resolve os problemas reais, enquanto Max e Surge estão lá fora entretendo a multidão.",
    imagem: "https://www.brawlstarsdicas.com.br/wp-content/uploads/2017/06/meg-wiki-brawl-stars-dicas-150x150.png",
  },
  {
    id: 9,
    nome: "Jessie",
    classe: "Controle",
    raridade: "Super-Raro",
    descricao: "Apesar de ser um verdadeiro prodígio e construir armas com sucata, Jessie não passa de uma garotinha aos olhos de sua mãe, Pam.",
    imagem: "https://www.brawlstarsdicas.com.br/wp-content/uploads/2017/06/jessie-wiki-brawl-stars-dicas-150x150.png",
  },
  {
    id: 10,
    nome: "Sprout",
    classe: "Detonadores",
    raridade: "Mítico",
    descricao: "Sprout parece ser um robô jardineiro fofo que ajuda a Rosa no Biodomo, mas na verdade é um incubador com braços e rodas para uma estranha semente rosa!",
    imagem: "https://www.brawlstarsdicas.com.br/wp-content/uploads/2017/06/sprout-wiki-brawl-stars-dicas-150x150.png",
  },
  {
    id: 11,
    nome: "Tick",
    classe: "Detonadores",
    raridade: "Super-Raro",
    descricao: "Tick segue a Penny como um animal de estimação enquanto ela planeja seu próximo grande esquema. Ele não serve para muita coisa além de explodir coisas, mas geralmente isso é suficiente!",
    imagem: "https://www.brawlstarsdicas.com.br/wp-content/uploads/2017/06/tick-wiki-brawl-stars-dicas-150x150.png",
  },
  {
    id: 12,
    nome: "Mortis",
    classe: "Algoz",
    raridade: "Mítico",
    descricao: "Mortis tinha grandes projetos com agente funerário e vampiro, mas, como ainda não tem ninguém com o pé na cova no Starr Park, os negócios vão de mal a pior.",
    imagem: "https://www.brawlstarsdicas.com.br/wp-content/uploads/2019/04/mortis-wiki-brawl-stars-dicas-150x150.png",
  },
   {
    id: 13,
    nome: "Kaze",
    classe: "Algoz",
    raridade: "Ultra-Lendário",
    descricao: "Kaze foi criada por seus pais para ser uma arma implacável, mas não por vontade própria. Ela fugiu para o Starr Park com Kenji e agora pode fazer suas próprias escolhas. Mesmo assim, vive dividida entre ser uma gueixa ou uma ninja mortal.",
    imagem: "https://www.brawlstarsdicas.com.br/wp-content/uploads/2017/06/kaze-wiki-brawl-stars-dicas-A3vNab-150x150.png.webp",
  },
  {
     id: 14,
    nome: "Sirius",
    classe: "Controle",
    raridade: "Ultra-Lendário",
    descricao: "Sua identidade é tão misteriosa quanto seus poderes. Ele foi a primeira atração do Starr Park, mas rumores dizem que foi expulso de forma injusta e banido para sempre. Agora... ele voltou para se vingar.",
    imagem: "https://www.brawlstarsdicas.com.br/wp-content/uploads/2017/06/sirius-wiki-brawl-stars-dicas-phuxcM-150x150.gif",
  }
];